composer.json, src/ComposerPlugin.php
Implemented method stubs for additional abstract methods in the PluginInterface interface
=> Composer 2.0 PluginInterface compatibility

README.md, composer.json, src/BomJsonWriter.php, src/ComposerCommandProvider.php, src/Model/Component.php, tests/BomJsonWriterTest.php, tests/schema/bom-1.2.schema-SNAPSHOT.json
=> Initial JSON support

.github/workflows/php.yml, composer.json, tools/composer-unused/.gitignore, tools/composer-unused/composer.json
=> QA tool: composer-unused 

.github/workflows/php.yml, .psalm/README.md, .psalm/baseline-lowest.xml, composer.json, tools/composer-require-checker/.gitignore, tools/composer-require-checker/composer.json
=> QA tool: composer-require-checker

.github/workflows/php.yml, HISTORY.md, README.md
=> CI: PHP-CS-fixer

.github/workflows/php.yml, .psalm/README.md
=> CI: composer uses caching

.github/dependabot.yml, demo/README.md
=> dependabot marked vendored demos to exclude

demo/README.md, demo/laravel-7.12.0/README.md, demo/laravel-7.12.0/project/composer.json, demo/laravel-7.12.0/project/composer.lock, demo/laravel-7.12.0/project/composer.template.lock, demo/laravel-7.12.0/results/bom.json, demo/laravel-7.12.0/results/bom.xml
related to issue #58
related to  https://github.com/CycloneDX/sbom-examples/pull/8#issuecomment-826095934
=> demo for `laravel/laravel:7.12.0`

composer.json
fixes https://packagist.org/packages/composer/composer/advisories?version=5072489
=> bump dev-dependency "composer" to 2.0.13 or higher

composer.json
fixes https://packagist.org/packages/composer/composer/advisories?version=5072489
=> bump dev-dependency "composer" to 1.10.22 or higher

.github/workflows/php.yml
=> added CI tests for reproducible demos

HISTORY.md, README.md, src/ComposerCommandProvider.php
preparation of #74
this will result in a feature release. probably `2.1.0`
=> added CLI option `--output-format`

.github/workflows/php.yml, composer.json, tools/composer-normalize/.gitignore, tools/composer-normalize/composer.json, tools/composer-unused/composer.json, tools/php-cs-fixer/composer.json, tools/psalm/composer.json
* added composr-normalizer tool
* added tests in CI for it
* normalized all `composer.json` files
=> add composr-normalizer

.github/workflows/demo.yml, .github/workflows/php.yml, composer.json, demo/laravel-7.12.0/project/composer.lock, demo/local/project/composer.lock
=> support php8.1

.github/workflows/php-dev.yml
Signed-off-by: Jan Kowalleck <jan.kowalleck@gmail.com>
=> CI assure dev-setup

.github/workflows/php.yml, HISTORY.md, composer.json, src/Builders/ComponentBuilder.php, src/MakeBom/Command.php, src/MakeBom/Factory.php, tests/Builders/ComponentBuilderTest.php, tests/MakeBom/FactoryTest.php
* Compatibility to composer v2.0.0 to v2.0.4 were improved
* Possible crashes when composer was not able to detect component's version properly
=> Bugfix compatibility for composer<2.0.5

HISTORY.md, composer.json, demo/laravel-7.12.0/README.md, demo/laravel-7.12.0/project/composer.lock, demo/laravel-7.12.0/results/bom.1.1.xml, demo/laravel-7.12.0/results/bom.1.2.json, demo/laravel-7.12.0/results/bom.1.2.xml, demo/laravel-7.12.0/results/bom.1.3.json, demo/laravel-7.12.0/results/bom.1.3.xml, demo/local/README.md, demo/local/project/composer.json, demo/local/project/composer.lock, demo/local/project/packages/local-demo-dependency/composer.json, demo/local/results/bom.1.1.xml, demo/local/results/bom.1.2.json, demo/local/results/bom.1.2.xml, demo/local/results/bom.1.3.json, demo/local/results/bom.1.3.xml, demo/symfony/example-results/bom.json, demo/symfony/example-results/bom.xml, src/Builders/BomBuilder.php, src/Builders/ComponentBuilder.php, src/Builders/ExternalReferenceRepositoryBuilder.php, src/Plugin.php, tests/Builders/ComponentBuilderTest.php, tests/Builders/ExternalReferenceRepositoryBuilderTest.php
fixes #129
* The resulting SBoM hold ExternalReferences as fetched from package descriptions.
=> add ExternalReferences

HISTORY.md, composer.json, demo/laravel-7.12.0/project/composer.lock, demo/laravel-7.12.0/results/bom.1.1.xml, demo/laravel-7.12.0/results/bom.1.2.json, demo/laravel-7.12.0/results/bom.1.2.xml, demo/laravel-7.12.0/results/bom.1.3.json, demo/laravel-7.12.0/results/bom.1.3.xml, demo/local/project/composer.json, demo/local/project/composer.lock, demo/local/project/packages/local-demo-issue-158/composer.json, demo/local/results/bom.1.1.xml, demo/local/results/bom.1.2.json, demo/local/results/bom.1.2.xml, demo/local/results/bom.1.3.json, demo/local/results/bom.1.3.xml
=> fix issue #158

.github/workflows/demo.yml, .github/workflows/php-dev.yml, .github/workflows/php.yml
=> CI: gh-workflows use php8.1

.github/workflows/demo.yml, composer.json, demo/laravel-7.12.0/project/composer.json, demo/laravel-7.12.0/project/composer.lock, demo/local/project/composer.json, demo/local/project/composer.lock, demo/symfony/project/composer.json, tools/composer-normalize/composer.json, tools/composer-unused/composer.json, tools/psalm/composer.json
composer v2.2 was released - https://github.com/composer/composer/releases/tag/2.2.0
add support for it in preparation for #153
=> Support composer 2.2

.github/workflows/php-dev.yml, CONTRIBUTING.md, tools/composer-require-checker/composer.json
=> dev-setup: drop php 7.3 support

HISTORY.md, composer.json, demo/laravel-7.12.0/project/composer.lock, demo/local/project/composer.lock, demo/symfony/example-results/bom.json, demo/symfony/example-results/bom.xml, src/MakeBom/Command.php
* Changed
* Raised dependency `cyclonedx/cyclonedx-library:^1.4.2`, was `cyclonedx/cyclonedx-library:^1.3.1`.
* Misc
* Adjusted internal typing and typehints.
* updated demo files
=> bump dependency `cyclonedx/cyclonedx-library`

.php-cs-fixer.dist.php, HISTORY.md, NOTICE, src/Builders/BomBuilder.php, src/Builders/ComponentBuilder.php, src/Builders/ExternalReferenceRepositoryBuilder.php, src/Factories/LicenseFactory.php, src/Factories/PackageUrlFactory.php, src/Factories/SpecFactory.php, src/MakeBom/Command.php, src/MakeBom/Exceptions/LockerIsOutdatedError.php, src/MakeBom/Exceptions/ValueError.php, src/MakeBom/Factory.php, src/MakeBom/Options.php, src/Plugin.php, src/ToolUpdater.php, tests/Builders/BomBuilderTest.php, tests/Builders/ComponentBuilderTest.php, tests/Builders/ExternalReferenceRepositoryBuilderTest.php, tests/Factories/LicenseFactoryTest.php, tests/Factories/PackageUrlFactoryTest.php, tests/Factories/SpecFactoryTest.php, tests/MakeBom/CommandTest.php, tests/MakeBom/FactoryTest.php, tests/MakeBom/OptionsTest.php, tests/PluginTest.php, tests/ToolUpdaterTest.php
as agreed via #242
closes #242
=> transfere copyright to OWASP Foundation.

src/Builder.php, tools/psalm/composer.json
=> Next dependabot/composer/tools/psalm/vimeo/psalm 5.1.0

HISTORY.md, src/Builder.php
=> Root component's versions unset on undetectable

.composer-require-checker.json, HISTORY.md, demo/devReq/results/bom.1.4.json, demo/devReq/results/bom.1.4.xml, demo/laravel-7.12.0/results/bom.1.4.json, demo/laravel-7.12.0/results/bom.1.4.xml, demo/local/results/bom.1.4.json, demo/local/results/bom.1.4.xml, demo/symfony/example-results/bom.json, demo/symfony/example-results/bom.xml, src/Builder.php, src/MakeBom/Command.php
=> populate `metadata.tools.tool.externalReferences`

HISTORY.md, demo/symfony/example-results/bom.json, demo/symfony/example-results/bom.xml, src/Builder.php, src/MakeBom/Command.php, tools/composer-require-checker/composer.json
=> have `serialNumber` populated

src/Builder.php
=> Remove iterator to array

.github/ISSUE_TEMPLATE/ValidationError-report.md, .github/workflows/demo.yml, HISTORY.md, README.md, src/MakeBom/Command.php, src/Plugin.php, tests/PluginTest.php
=> feat: deprecate composer command `make-bom`,  create composer command `CycloneDX:make-sbom`

demo/devReq/README.md, demo/devReq/project/composer.json, demo/laravel-7.12.0/README.md, demo/laravel-7.12.0/project/composer.json, demo/local/README.md, demo/local/project/composer.json, demo/symfony/README.md, demo/symfony/project/composer.json
=> fix demo data builder

HISTORY.md, demo/devReq/results/bom.1.3.json, demo/devReq/results/bom.1.3.xml, demo/devReq/results/bom.1.4.json, demo/devReq/results/bom.1.4.xml, demo/laravel-7.12.0/results/bom.1.3.json, demo/laravel-7.12.0/results/bom.1.3.xml, demo/laravel-7.12.0/results/bom.1.4.json, demo/laravel-7.12.0/results/bom.1.4.xml, demo/local/results/bom.1.3.json, demo/local/results/bom.1.3.xml, demo/local/results/bom.1.4.json, demo/local/results/bom.1.4.xml, demo/symfony/example-results/bom.json, demo/symfony/example-results/bom.xml, src/MakeBom/Builder.php, src/Properties.php
=> Dist source reference

demo/symfony/example-results/bom.json, demo/symfony/example-results/bom.xml, src/MakeBom/Builder.php, tools/composer-unused/composer.json
- downgrade `composer-unsued` tool, since 0.8.6 was yanked.
- bump CDX lib
- gen demos with latest lib
=> bump lib and gen demos

HISTORY.md, composer.json, src/MakeBom/Command.php
=> fix(typo): "compoer" -> "composer"

.github/workflows/php.yml
=> ci: test compoer v2.6

.github/workflows/demo.yml, HISTORY.md, demo/devReq/project/composer.json, demo/laravel-7.12.0/project/composer.json, demo/local/project/composer.json, demo/symfony/example-results/bom.json, demo/symfony/example-results/bom.xml, src/MakeBom/Builder.php, src/MakeBom/Command.php, src/MakeBom/Options.php, tests/MakeBom/BuilderTest.php
=> add info to SBOM results: which version of `composer`  was used in the process

HISTORY.md, src/MakeBom/Builder.php
=> try tool version detection in global env

.github/workflows/php-dev.yml, .github/workflows/php.yml, HISTORY.md, tools/composer-normalize/composer.json, tools/php-cs-fixer/composer.json, tools/phpunit/composer.json, tools/psalm/composer.json
php8.3 was released. 
see https://wiki.php.net/todo/php83
=> support  php8.3

.github/workflows/php.yml, HISTORY.md
=> feat: support composer 2.7 2.8
